/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32 VS Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "../Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_sai.h"

#define BUFFER_SIZE 256
int32_t AudioBufferIn[BUFFER_SIZE];
int32_t AudioBufferOut[BUFFER_SIZE];

int main(void)
{
    // Initialize system
    HAL_Init();
    SystemClock_Config();

    // Initialize GPIO
    MX_GPIO_Init();
    
    // Initialize audio interface
    MX_SAI2_Init();
        
    while (1)
    {
        // Main loop
        HAL_Delay(100);
    }
}

void ProcessAudio(int32_t* input, int32_t* output, uint32_t size)
{
    // Simple passthrough for testing
    for(uint32_t i = 0; i < size; i++)
    {
        output[i] = input[i];
    }
}

void HAL_SAI_RxCpltCallback(SAI_HandleTypeDef *hsai)
{
    // Process audio when DMA buffer is full
    ProcessAudio(AudioBufferIn, AudioBufferOut, BUFFER_SIZE);
}